version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    command: python run.py
    depends_on:
      - db

  db:
    image: alpine
    volumes:
      - ./data:/data
    command: sh -c "mkdir -p /data && touch /data/users.db"

  locust:
    build: .
    volumes:
      - .:/app
    ports:
      - "8089:8089"
    command: locust -f /app/locustfile.py --host http://web:8000
    depends_on:
      - web

volumes:
  data: